apiVersion: v1
kind: Config
clusters:
- name: "kong-ingress-v5-29-production"
  cluster:
    server: "https://rancher.mynt.xyz/k8s/clusters/c-2gzrx"
    certificate-authority-data: "LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUJ2VENDQ\
      VdPZ0F3SUJBZ0lCQURBS0JnZ3Foa2pPUFFRREFqQkdNUnd3R2dZRFZRUUtFeE5rZVc1aGJXbGoKY\
      kdsemRHVnVaWEl0YjNKbk1TWXdKQVlEVlFRRERCMWtlVzVoYldsamJHbHpkR1Z1WlhJdFkyRkFNV\
      FkzT1RJNQpOak16TURBZUZ3MHlNekF6TWpBd056RXlNVEJhRncwek16QXpNVGN3TnpFeU1UQmFNR\
      Vl4SERBYUJnTlZCQW9UCkUyUjVibUZ0YVdOc2FYTjBaVzVsY2kxdmNtY3hKakFrQmdOVkJBTU1IV\
      1I1Ym1GdGFXTnNhWE4wWlc1bGNpMWoKWVVBeE5qYzVNamsyTXpNd01Ga3dFd1lIS29aSXpqMENBU\
      VlJS29aSXpqMERBUWNEUWdBRXU4dUNGb2p6UjBuSgpHbEU0NUYyaTNRRmdsMW81cVAzaFROTHJiK\
      0J5Z21QaGVSZmlLR1E4bjI1a1lva1V3aFBERTJYNkNpQjVic09pCll3WHZla2NuM0tOQ01FQXdEZ\
      1lEVlIwUEFRSC9CQVFEQWdLa01BOEdBMVVkRXdFQi93UUZNQU1CQWY4d0hRWUQKVlIwT0JCWUVGQ\
      XJMbzFiWmV0VGhPZEdpRHNYbjNpV2xaeUNmTUFvR0NDcUdTTTQ5QkFNQ0EwZ0FNRVVDSVFEdgpJZ\
      VR6OVVWdkJVbnJqMWZYM2x2ZTZwUnFVUlVZQWx2MnNaTlR2Y3NwcUFJZ1dON1JabkZIZldCRjFxZ\
      GdLekw0Clg5aVluYklTU0hqeU1ZOStnN3FUbWdVPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0t"

users:
- name: "kong-ingress-v5-29-production"
  user:
    token: "kubeconfig-u-dt5l5ntabzhq6l5:85t8psjkfzbvs4mw2mq5zcjh2vmmcpt7n7lxjf8mqdw4krvmphk6m8"


contexts:
- name: "kong-ingress-v5-29-production"
  context:
    user: "kong-ingress-v5-29-production"
    cluster: "kong-ingress-v5-29-production"

current-context: "kong-ingress-v5-29-production"
